services:
  postgres:
    image: postgres:16-alpine
    container_name: travel_db
    environment:
      POSTGRES_USER: travel_user
      POSTGRES_PASSWORD: travel_pass
      POSTGRES_DB: travel_connect
    ports:
      - "5433:5432"    # ← đổi 5432 thành 5433
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: travel_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: